import os
import json
import re
import google.generativeai as genai
from typing import List, Dict

class AIProcessor:
    """Dokari AI Processor for documentation generation and Q&A chat using Google Gemini with fallback models"""
    
    def __init__(self):
        # Load .env file from project root or current folder if present
        api_key = os.getenv('GEMINI_API_KEY') or os.getenv('GOOGLE_API_KEY') or os.getenv('OPENAI_API_KEY')
        if not api_key:
            possible_env_paths = [
                os.path.join(os.path.dirname(__file__), '..', '.env'),
                os.path.join(os.path.dirname(__file__), '.env'),
                '.env'
            ]
            for env_path in possible_env_paths:
                if os.path.exists(env_path):
                    try:
                        with open(env_path, 'r', encoding='utf-8') as f:
                            for line in f:
                                line = line.strip()
                                if line and not line.startswith('#') and '=' in line:
                                    k, v = line.split('=', 1)
                                    k, v = k.strip(), v.strip().strip('"\'')
                                    os.environ[k] = v
                    except Exception:
                        pass
                    break
            api_key = os.getenv('GEMINI_API_KEY') or os.getenv('GOOGLE_API_KEY') or os.getenv('OPENAI_API_KEY')

        if api_key:
            os.environ['GOOGLE_API_KEY'] = api_key
            os.environ['GEMINI_API_KEY'] = api_key
            genai.configure(api_key=api_key)

        self.system_prompt = "You are Dokari, an expert software architecture and technical documentation AI. Your sole objective is to write highly accurate, comprehensive, and professional documentation strictly derived from the provided source code files. Do not use any icons or emojis."
        # Ordered list of fallback models to cycle through on quota errors (429)
        self.models_fallback = [
            "gemini-2.5-flash",
            "gemini-2.5-flash-lite",
            "gemini-3.1-flash-lite",
            "gemini-flash-lite-latest",
            "gemini-3-flash-preview"
        ]

    def _generate_content_with_fallback(self, contents, system_instruction=None, generation_config=None, requested_model=None):
        """Generates content using a list of fallback models if quota is exceeded"""
        models = self.models_fallback
        if requested_model:
            models = [requested_model] + self.models_fallback
            
        last_exception = None
        for model_name in models:
            try:
                model = genai.GenerativeModel(
                    model_name=model_name,
                    system_instruction=system_instruction
                )
                config = generation_config or {}
                response = model.generate_content(contents, generation_config=config)
                return response
            except Exception as e:
                err_str = str(e)
                # Check for quota or rate limit errors
                if "429" in err_str or "quota" in err_str.lower() or "limit" in err_str.lower():
                    print(f"Model {model_name} rate limited or quota exceeded. Trying fallback... Error: {err_str[:150]}")
                    last_exception = e
                    continue
                else:
                    # For other types of errors, raise immediately
                    raise e
        # If all models failed, raise the last exception
        if last_exception:
            raise last_exception
        raise Exception("No fallback models succeeded")
    
    def generate_api_documentation(self, files_content: List[Dict], requested_model: str = None) -> str:
        """Generate API documentation strictly grounded in uploaded code files"""
        prompt = self._create_api_doc_prompt(files_content)
        
        try:
            response = self._generate_content_with_fallback(
                prompt,
                system_instruction=self.system_prompt,
                requested_model=requested_model
            )
            return f"""# Dokari Generated API Documentation

{response.text}

---
*Generated by Dokari - AI-Powered Technical Documentation Companion*
"""
        except Exception as e:
            return f"""# API Documentation

## Overview
This documentation was generated by Dokari.

## Endpoints
Documentation generation encountered an issue. Please check your Gemini API configuration.

**Error:** {str(e)}

---
*Dokari - Making documentation easy*
"""
    
    def generate_readme(self, project_info: Dict, files_content: List[Dict], requested_model: str = None) -> str:
        """Generate README.md content directly based on all source code files"""
        files_details = ""
        for file in files_content:
            fname = file.get('name') or file.get('filename') or 'unnamed_file'
            files_details += f"\n--- Source File: {fname} ---\n"
            files_details += file.get('content', '')[:30000]
            files_details += "\n"

        file_names_list = [f.get('name') or f.get('filename') or '' for f in files_content]
        file_names_str = ", ".join([fn for fn in file_names_list if fn])

        prompt = f"""You are Dokari. Generate a comprehensive, high-quality README.md in markdown format. 
Your generated README MUST be strictly accurate and directly reflect the code implementation in the uploaded source files below.

Project Name: {project_info.get('name', 'Dokari Project')}
Description: {project_info.get('description', 'Technical project documented with Dokari')}
Uploaded Codebase Files: {file_names_str}

Source Files Code Context:
{files_details}

STRICT INSTRUCTIONS:
1. Base every feature, function explanation, and usage snippet directly on the actual classes, functions, and modules in the source files above.
2. Structure the README with clear headers:
   - # Project Name & Description
   - ## Features & Capabilities (Derived directly from the code)
   - ## Architecture & Component Breakdown (Detailing each uploaded file: {file_names_str})
   - ## API & Module Reference (Listing classes, functions, parameters, and return types)
   - ## Usage & Execution Examples (Concrete examples showing how to invoke the classes/functions in the code)
3. Do not include generic placeholder text.
4. Do not include any icons or emojis in the markdown response.
"""
        
        try:
            response = self._generate_content_with_fallback(
                prompt,
                system_instruction=self.system_prompt,
                requested_model=requested_model
            )
            return f"""{response.text}

---
## Documentation Status

This README was automatically generated by Dokari
Last updated: {self._get_current_timestamp()}
For manual edits, modify this file directly
"""
        except Exception as e:
            return f"""# {project_info.get('name', 'Dokari Project')}

## Description
{project_info.get('description', 'A project documented with Dokari')}

## Quick Start
Documentation generation encountered an issue. Please check your configuration.

**Error:** {str(e)}

---
*Generated with Dokari - AI Documentation Generator*
"""

    def generate_chat_answer(self, files_content: List[Dict], question: str, history: List[Dict]) -> str:
        """Answer code-related Q&A chat questions based on uploaded files context"""
        prompt = "You are the Dokari AI Companion, an expert software developer. Below are the exact source code files uploaded to this workspace.\n\nProject Code Base Context:\n"
        for file in files_content:
            fname = file.get('name') or file.get('filename') or 'unnamed_file'
            prompt += f"--- File: {fname} ---\n"
            prompt += file.get('content', '')[:30000]
            prompt += "\n"
        
        system_prompt = "You are the Dokari AI Companion, a helpful and precise technical assistant. Answer the user's questions strictly based on the provided project files context. Do not use icons or emojis in your answers."
        
        # Build contents structure for Gemini
        contents = []
        # Add files context first
        contents.append({"role": "user", "parts": [prompt]})
        contents.append({"role": "model", "parts": ["I have loaded the complete source files into context. I am ready to answer technical questions about this exact codebase."]})
        
        # Add history
        for msg in history[-6:]:
            role = "model" if msg['sender'] == 'ai' else "user"
            contents.append({"role": role, "parts": [msg['text']]})
            
        # Add current question
        contents.append({"role": "user", "parts": [question]})
        
        try:
            response = self._generate_content_with_fallback(
                contents,
                system_instruction=system_prompt
            )
            return response.text
        except Exception as e:
            return f"Chat request encountered an error: {str(e)}"

    def analyze_doc_health(self, files_content: List[Dict]) -> Dict:
        """Analyze the documentation coverage of files and return score + suggestions"""
        if not files_content:
            return {
                "score": 0,
                "suggestions": ["No files uploaded yet. Upload files to calculate your Dokari Health Score."]
            }
            
        prompt = "Analyze the documentation quality of these exact source code files. Evaluate comment densities, docstring existences, class/method explanations, and clarity. Return ONLY a valid JSON object with the keys 'score' (an integer from 0 to 100 based on documentation coverage) and 'suggestions' (a list of 2 to 4 concise technical recommendations explicitly naming functions or classes in the code that lack docstrings, e.g., 'Add class docstring to main.py:Calculator'). Do not include markdown fences or extra text, just raw JSON. Do not use any icons or emojis.\n\nSource Code Files:\n"
        for file in files_content:
            fname = file.get('name') or file.get('filename') or 'unnamed_file'
            prompt += f"--- File: {fname} ---\n"
            prompt += file.get('content', '')[:15000]
            prompt += "\n"
            
        try:
            # Enforce JSON mime-type dynamically via Gemini config
            response = self._generate_content_with_fallback(
                prompt,
                generation_config={"response_mime_type": "application/json"}
            )
            
            raw_content = response.text.strip()
            data = json.loads(raw_content)
            return {
                "score": int(data.get("score", 50)),
                "suggestions": list(data.get("suggestions", ["Improve method documentation"]))
            }
        except Exception as e:
            error_log = f"Failed to analyze doc health: {str(e)}"
            print(error_log)
            return {
                "score": 50,
                "suggestions": ["Failed to run AI static analysis. Check Gemini configuration."]
            }
    
    def _create_api_doc_prompt(self, files_content: List[Dict]) -> str:
        """Create prompt for API documentation strictly grounded in the uploaded files"""
        prompt = """Analyze the following source code files and generate comprehensive, precise API documentation in markdown format. Do not use icons or emojis.

CRITICAL REQUIREMENTS:
1. Base 100% of the documentation on the actual classes, functions, routes, methods, parameter names, and return structures defined in the code files below.
2. For each file, provide a clear breakdown:
   - File & Module Overview
   - Classes & Structs (with constructor parameters and attributes)
   - Methods & Functions (with exact parameter names, type hints if present, and detailed explanations of logic)
   - Endpoint / Route Definitions (if web framework routes like Flask, Express, or PHP routes are detected)
   - Code Usage Example

Code files to analyze:
"""
        
        for file in files_content:
            fname = file.get('name') or file.get('filename') or 'unnamed_file'
            prompt += f"\n### File: {fname}\n```\n"
            prompt += file.get('content', '')[:30000]
            prompt += "\n```\n"
        
        prompt += "\nGenerate exhaustive, well-structured API documentation strictly matching the code above."
        return prompt
    
    def _get_current_timestamp(self) -> str:
        """Get current timestamp for documentation"""
        from datetime import datetime
        return datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    @staticmethod
    def _normalize_mermaid_diagram(content: str) -> str:
        """Remove common model formatting mistakes before Mermaid parses the diagram."""
        content = content.replace('\ufeff', '').strip()
        content = re.sub(r'^```(?:mermaid)?\s*', '', content, count=1, flags=re.IGNORECASE)
        content = re.sub(r'\s*```\s*$', '', content, count=1)

        lines = content.splitlines()
        start = next(
            (index for index, line in enumerate(lines)
             if re.match(r'^\s*(?:graph|flowchart)\s+(?:TB|TD|BT|RL|LR)\b', line, re.IGNORECASE)),
            None
        )
        if start is not None:
            lines = lines[start:]

        normalized = []
        subgraph_index = 0
        for line in lines:
            subgraph_match = re.match(r'^(\s*)subgraph\s+(.+?)\s*$', line, re.IGNORECASE)
            if subgraph_match and '[' not in subgraph_match.group(2):
                subgraph_index += 1
                title = subgraph_match.group(2).replace('"', "'")
                line = f'{subgraph_match.group(1)}subgraph Layer{subgraph_index}["{title}"]'

            line = re.sub(
                r'^(\s*)([A-Za-z][A-Za-z0-9_]*)\s+-->(?:\s+)([A-Za-z][A-Za-z0-9_]*)\s+--\s*(.+?)\s*$',
                r'\1\2 -->|\4| \3',
                line
            )

            line = re.sub(
                r'(?P<source>\b[A-Za-z][A-Za-z0-9_]*)\s+--\s*'
                r'(?P<label>[^-\n]+?)\s*-->\s*'
                r'(?P<target>[A-Za-z][A-Za-z0-9_]*)\s*'
                r'(?:\((?P<details>[^()\n]+)\))?\s*$',
                lambda match: (
                    f"{match.group('source')} -->|{match.group('label').strip()}| "
                    f"{match.group('target')}"
                ),
                line
            )

            line = re.sub(
                r'(?P<source>\b[A-Za-z][A-Za-z0-9_]*)\s+'
                r'(?P<arrow>-->|-.->|==>|---)\s*'
                r'(?P<target>[A-Za-z][A-Za-z0-9_]*)\s*\((?P<label>[^()\n]+)\)\s*$',
                lambda match: (
                    f"{match.group('source')} {match.group('arrow')}|"
                    f"{match.group('label').strip()}| {match.group('target')}"
                ),
                line
            )
            normalized.append(line.rstrip())

        return '\n'.join(normalized).strip()

    def generate_architecture_mermaid(self, codebase_structure: dict, requested_model: str = None) -> str:
        """Generates a highly accurate Mermaid.js architecture diagram representing the actual uploaded files"""
        files = codebase_structure.get('files', [])
        if not files:
            return 'graph TD\n    NoFiles["No uploaded files to map"]'
            
        prompt = """Analyze the following source code files and generate a professional, accurate, and legit architectural design diagram in Mermaid.js flowchart syntax (e.g. `graph TD` or `graph LR`).
        
        CRITICAL REQUIREMENTS:
        1. Model the actual architecture of the uploaded codebase. Group components into realistic layers (e.g. Frontend/UI components, Controllers/Routes, Service Layers/Logic, Database Models/Clients, external integrations).
        2. Create nodes for each module/file and draw clean directional dependency/flow arrows (e.g. Controller --> Service) showing how data flows and which components import or use each other.
        3. Do NOT wrap the mermaid code in any markdown fences (like ```mermaid or ```). Return ONLY the raw Mermaid diagram text starting directly with `graph TD` or `graph LR` or other valid Mermaid graph types.
        4. Do not use icons, emojis, or external markdown assets.
        5. VERY IMPORTANT: Node identifiers in Mermaid must contain only letters, numbers, and underscores. Put every human-readable node label in double quotes inside brackets, e.g. `MainPy["main.py"]`.
        6. Use only standard Mermaid flowchart grammar. Edge labels MUST use `Source -->|label| Target`; never append parenthetical text after a node. Keep subgraph declarations in the form `subgraph LayerId["Layer title"]`.
        7. Do not use parentheses, slashes, brackets, or hyphens outside quoted node labels and edge labels. Do not add explanatory prose or comments.
        
        Files to analyze:
        """
        
        for file in files:
            fname = file.get('name') or file.get('filename') or 'unnamed_file'
            prompt += f"\n--- File: {fname} ---\n"
            prompt += file.get('content', '')[:15000]
            prompt += "\n"
            
        try:
            response = self._generate_content_with_fallback(prompt, requested_model=requested_model)
            return self._normalize_mermaid_diagram(response.text)
        except Exception as e:
            error_message = str(e).replace('"', "'").replace('\n', ' ')
            return f'graph TD\n    Error["Error generating architecture diagram: {error_message}"]'